---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-app
bases:
  - ../../base
resources:
  - resources/microservice.yml
secretGenerator:
  - name: apiv1-flyway-conf
    files:
      - flyway.conf
  - name: apiv1-conf
    envs:
      - env.properties
    type: Opaque
